version: 2
updates:
  - package-ecosystem: "npm"
    directory: "apps/next/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "apps/vue/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "."
    schedule:
      interval: "weekly"