version: 2
updates:
  - package-ecosystem: "npm"
    directory: "client/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "server/"
    schedule:
      interval: "weekly"