services:
  client:
    restart: always
    working_dir: /app
    build:
      context: .
      dockerfile: docker/vue/Dockerfile
      target: dev
      args:
        BUN_VERSION: ${BUN_VERSION:-1.3.3}
        NODE_VERSION: ${NODE_VERSION:-22.20.0}
        APP_PORT: ${CLIENT_PORT:-5173}
    env_file:
      - .env
    ports:
      - 8081:5173
    volumes:
      - ./client:/app
      # - /app/node_modules
      - client_node_modules:/app/node_modules

  server:
    platform: linux/amd64
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.12}
        APP_PORT: ${SERVER_PORT:-8000}
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app/server
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./uv.lock:/app/uv.lock:ro
      # ✅ Préserve le .venv de l'image
      # - /app/.venv
      - server_venv:/app/.venv
    restart: always

volumes:
  client_node_modules:
  server_venv: