name: CI â€“ Linting

on:
  workflow_call:
    inputs:
      python-version:
        description: Python version used to run tests
        required: true
        type: string
      node-version:
        description: "Node.js version to use"
        required: true
        type: string
      bun-image:
        description: "Bun image to use"
        required: true
        type: string

jobs:
  lint-server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ${{ inputs.python-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ runner.os }}-py-${{ inputs.python-version }}-${{ hashFiles('**/pyproject.toml', '**/requirements.txt') }}
          restore-keys: |
            pip-cache-${{ runner.os }}-py-

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Set up Python ${{ inputs.python-version }}
        run: uv python install ${{ inputs.python-version }}

      - name: Lint server
        run: |
          uv sync --dev
          uv run ruff check
          uv run ty check

  lint-next:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache bun
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
            apps/next/node_modules
          key: bun-cache-${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('apps/next/bun.lockb', 'apps/next/package.json') }}
          restore-keys: |
            bun-cache-${{ runner.os }}-node-

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        working-directory: ./apps/next
        run: |
          bun install --frozen-lockfile
          bun lint

  lint-vue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache bun
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
            apps/vue/node_modules
          key: bun-cache-${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('apps/vue/bun.lockb', 'apps/vue/package.json') }}
          restore-keys: |
            bun-cache-${{ runner.os }}-node-

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        working-directory: ./apps/vue
        run: |
          bun install --frozen-lockfile
          bun lint
