name: Versions

on:
  workflow_call:

jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.set.outputs.python-version }}
      node-version: ${{ steps.set.outputs.node-version }}
      pnpm-version: ${{ steps.set.outputs.pnpm-version }}
      app-port: ${{ steps.set.outputs.app-port }}
    steps:
      - name: Set versions
        id: set
        run: |
          echo "python-version=3.x" >> $GITHUB_OUTPUT
          echo "node-version=22.20.0" >> $GITHUB_OUTPUT
          echo "pnpm-version=10.18.3" >> $GITHUB_OUTPUT
          echo "app-port=5173" >> $GITHUB_OUTPUT

      - name: Output versions
        run: |
          echo "Python: ${{ steps.set.outputs.python-version }}"
          echo "Node.js: ${{ steps.set.outputs.node-version }}"
          echo "pnpm: ${{ steps.set.outputs.pnpm-version }}"
          echo "App Port: ${{ steps.set.outputs.app-port }}"
